# Generated by Django 5.2.1 on 2025-05-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
