# Generated by Django 5.2.1 on 2025-06-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_post_content_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
